workspace:
    base: /go

pipeline:
    build:
        image: golang
        commands:
            - go get github.com/takawang/sugar
            - go test -v -bench . -benchmem
            - go build
            - cd example
            - go build
            - ./example
