language: go

go:
    - 1.5
    - 1.6
    - tip

before_install:
    - export TZ=Asia/Taipei

script:
    - go get github.com/takawang/sugar
    - go test -v -bench . -benchmem
    - go build
    #- cd example && go build && ./example

notifications:
    email: false
